blueprint:
  name: Window and emergency detection
  description: Automation to switch the TRV on or off depending on the window state. Optionally, the TRV can be automatically turned off when an emergency indicator is set.
  domain: automation
  source_url: https://github.com/mldytech/smarthome/blob/main/hass-blueprints/window-detection.yaml

  input:
    trv:
      name: Thermostat
      selector:
        entity:
          domain:
            - climate
          multiple: false
    window_sensor:
      name: Window / Door Sensor Group
      selector:
        entity:
          domain:
            - binary_sensor
            - input_boolean
          multiple: false
    window_on_delay:
      name: Window / Door Sensor ON-Delay
      description:
        Time in seconds after which the TRV turns on again if the window was closed.
      default: 120
      selector:
        number:
          mode: box
          min: 0.0
          max: 3600.0
          unit_of_measurement: seconds
          step: 1.0
    window_off_delay:
      name: Window / Door Sensor OFF-Delay
      description:
        Time in seconds after which the TRV turns off if the window was opened
      default: 5
      selector:
        number:
          mode: box
          min: 0.0
          max: 3600.0
          unit_of_measurement: seconds
          step: 1.0
    emergency_mode_chooser:
      name: Emergency mode chooser (Optional)
      description:
        Whether to enable / disable the emergency mode of this automation.
        The emergency mode will turn off the trv if either the temperature sensor
        is unavailable or the calibration entity is unavailable (triggered through calibration automation)
      default: false
      selector:
        boolean: {}
    emergency_mode_indicator:
      name: Emergency mode indicator (Optional)
      description:
        An input boolean which is set when the automation detects an emergency
        mode.
      default:
      selector:
        entity:
          domain:
            - input_boolean
          multiple: false
mode: restart
trigger:
  - platform: state
    entity_id: !input window_sensor
    to: "off"
    from: "on"
    for: !input window_on_delay
    id: window_off
  - platform: state
    entity_id: !input window_sensor
    to: "on"
    from: "off"
    for: !input window_off_delay
    id: window_on
variables:
  trv: !input trv
  emergency_mode_chooser: !input emergency_mode_chooser
  emergency_mode_indicator: !input emergency_mode_indicator
action:
  - if:
      - condition: template
        value_template: '{{ emergency_mode_chooser and states(emergency_mode_indicator) == "on" }}' #there is an emergency (emergency is e.g. set through calibration automation)
    then:
      - service: climate.set_hvac_mode
        entity_id: !input trv
        data:
          hvac_mode: "off" 
      - service: notify.notify_telegrams #TODO: Notify channel as input variable
        data:
          message: TRV-Emergency of {{ state_attr(trv, 'friendly_name')}} still active. Closing / Opening the window didn't change the state.
          title: TRV-Error
    else:
      - if:
          - condition: trigger
            id:
              - window_on
        then:
          - service: climate.set_hvac_mode
            data:
              hvac_mode: "off"
            entity_id: !input trv
          - delay:
              hours: 0
              minutes: 1
              seconds: 0
              milliseconds: 0
          - if: #notify if the trv didn't change it's state after 1 min
              - condition: state
                entity_id: !input trv
                state: heat
            then:
              - service: notify.notify_telegrams
                metadata: {}
                data:
                  message: TRV {{ state_attr(trv, 'friendly_name')}} is still heating although the window is open. An attempt is made to resolve the problem. It should be checked manually.
                  title: Caution
      - if:
          - condition: trigger
            id:
              - window_off
        then:
          - service: climate.set_hvac_mode
            data:
              hvac_mode: heat
            entity_id: !input trv
